[build]
builder = "nixpacks"

[deploy]
startCommand = "python backend/server.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[volumes]]
mountPath = "/app/backend"
name = "aquazul-db"
